name: Knowledge Distillation for Customer Support LLMs using Synthetic Data
description: | 
  Once all the initial setup steps are completed, follow the readme instructions and run all steps 0-3 to distill knowledge using Synthetic Data Studio for a customer support use case.
author: Andreas Tsiartas
specification_version: 1.0
prototype_version: 1.0
date: "2025-03-18"



runtimes:
  - editor: JupyterLab 
    kernel: Python 3.9 
    edition: Standard 

## Below are some sample tasks based on some of the most popular aspects of AMP creation.
tasks:

  ## SESSION related AMP snippet
  - type: run_session
    name: Install Dependencies
    script: 0_session-install-dependencies/install-dependencies.py
    short_summary: Install Requirements and Dependencies
    kernel: python3
    cpu: 4
    memory: 16

